os: Linux
dist: focal
language: node_js
node_js: 18.19.0
install: skip
script: sleep 1
deploy:
  provider: npm
  email: "arthana.h@celestialsys.com"
  api_key: "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"
  skip_cleanup: true
  on:
    tags: true


