os: Linux
dist: focal
language: node_js
node_js: 18.19.0
install: skip
script: sleep 1
deploy:
  provider: npm
  email: "arthana.h@celestialsys.com"
  api_key: "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"
  skip_cleanup: true
  on:
    all_branches: true


